server:
  #############################
  # Store server secrets here #
  #############################

  JWT_SIGN_PHRASE: '${ML_INSTALL_SERVER_SIGN_KEY}'

  # Plate Recognizer Cloud API key (They have a free tier!)
  # Platrec have other PAID services, I can potentially implement those as well if someone grants me access.
  PLATEREC_API_KEY:

  # WIP, I need to get someone to allow me access to their API creds to implement this. I'm cheap :)
  # Rekor also offers other services. I can potentially implement those as well.
  REKOR_KEY: